### PR TITLE
Adding config.json to MANIFEST.in

### PR DESCRIPTION
**Pull request by emarinier**
Adding the config file to the manifest file and moving inside the source directory, because when ~~Conda / Galaxy~~ pip installs it, it cannot find the config file.

Alternate solutions that leave `config.json` at the project root level have a potential problem in that they may be clobbered by other packages installed with pip that do the same. Since you end up with something like:

```
pip/
  - config.json
  - proksee/
  - proksee-1.0.0a3.dist-info/
```

### CODE REVIEW

**Comment by emarinier** [comment]
Cherry picking the quast=5.0.2 fix.

**Comment by emarinier** [comment]
This is probably better solved by adding the config file to the manifest: https://github.com/proksee-project/proksee-cmd/blob/develop/MANIFEST.in

**Comment by emarinier** [comment]
@ericenns Should be ready for review! :)

**Review by ericenns — APPROVED** [review]
I just tested this via the following:

1. clone repo
2. create virtualenv and then activate it
3. run `pip install .`
4. run `proksee updated`
5. inspect config in virtualenv which points to downloaded mash sketch

Based on my testing everything works as expected.

**Pull request merged**
